spring:
  datasource:
    url: jdbc:sqlserver://sql2022:1433;databaseName=FinancialPreference;encrypt=true;trustServerCertificate=true
    username: sa
    password: ${MSSQL_PASSWORD:}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 10000

logging:
  level:
    root: INFO
    com.esunbank: INFO
